// ─── OsanCarbon (ERC-1155 carbon credits, UUPS proxy) ────────────────────────
// CarbonProject struct: { name, methodology, region, vintage, linkedPropertyId,
//   totalIssued, totalRetired, verified, verifier, registryDocHash }
// RetirementRecord struct: { retirer, beneficiary, amount, timestamp, reason, registrySerial }
export const OsanCarbonAbi = [
  { type: "event", name: "ProjectCreated", inputs: [
    { name: "projectId",       type: "uint256", indexed: true  },
    { name: "name",            type: "string",  indexed: false },
    { name: "methodology",     type: "string",  indexed: false },
    { name: "region",          type: "string",  indexed: false },
    { name: "vintage",         type: "uint256", indexed: false },
    { name: "linkedPropertyId",type: "uint256", indexed: false },
  ]},
  { type: "event", name: "CreditsIssued", inputs: [
    { name: "projectId", type: "uint256", indexed: true  },
    { name: "amount",    type: "uint256", indexed: false },
    { name: "recipient", type: "address", indexed: true  },
  ]},
  { type: "event", name: "CreditsRetired", inputs: [
    { name: "projectId",     type: "uint256", indexed: true  },
    { name: "amount",        type: "uint256", indexed: false },
    { name: "retirer",       type: "address", indexed: true  },
    { name: "beneficiary",   type: "address", indexed: true  },
    { name: "reason",        type: "string",  indexed: false },
    { name: "registrySerial",type: "string",  indexed: false },
  ]},
  { type: "event", name: "ProjectVerified", inputs: [
    { name: "projectId", type: "uint256", indexed: true  },
    { name: "verifier",  type: "address", indexed: true  },
  ]},
  { type: "event", name: "FeeConfigUpdated", inputs: [
    { name: "feeRouter",   type: "address", indexed: true  },
    { name: "feeToken",    type: "address", indexed: true  },
    { name: "feePerCredit",type: "uint256", indexed: false },
  ]},
  { type: "event", name: "TransferSingle", inputs: [
    { name: "operator", type: "address", indexed: true  },
    { name: "from",     type: "address", indexed: true  },
    { name: "to",       type: "address", indexed: true  },
    { name: "id",       type: "uint256", indexed: false },
    { name: "value",    type: "uint256", indexed: false },
  ]},
  { type: "event", name: "TransferBatch", inputs: [
    { name: "operator", type: "address",   indexed: true  },
    { name: "from",     type: "address",   indexed: true  },
    { name: "to",       type: "address",   indexed: true  },
    { name: "ids",      type: "uint256[]", indexed: false },
    { name: "values",   type: "uint256[]", indexed: false },
  ]},
  { type: "event", name: "ApprovalForAll", inputs: [
    { name: "account",  type: "address", indexed: true  },
    { name: "operator", type: "address", indexed: true  },
    { name: "approved", type: "bool",    indexed: false },
  ]},
  { type: "event", name: "RoleGranted", inputs: [
    { name: "role",    type: "bytes32", indexed: true },
    { name: "account", type: "address", indexed: true },
    { name: "sender",  type: "address", indexed: true },
  ]},
  { type: "event", name: "RoleRevoked", inputs: [
    { name: "role",    type: "bytes32", indexed: true },
    { name: "account", type: "address", indexed: true },
    { name: "sender",  type: "address", indexed: true },
  ]},
  { type: "event", name: "Paused",   inputs: [{ name: "account", type: "address", indexed: false }] },
  { type: "event", name: "Unpaused", inputs: [{ name: "account", type: "address", indexed: false }] },
  // Read functions
  { type: "function", name: "projectCount", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getProject", inputs: [{ name: "projectId", type: "uint256" }],
    outputs: [{ name: "", type: "tuple", components: [
      { name: "name",             type: "string"  },
      { name: "methodology",      type: "string"  },
      { name: "region",           type: "string"  },
      { name: "vintage",          type: "uint256" },
      { name: "linkedPropertyId", type: "uint256" },
      { name: "totalIssued",      type: "uint256" },
      { name: "totalRetired",     type: "uint256" },
      { name: "verified",         type: "bool"    },
      { name: "verifier",         type: "address" },
      { name: "registryDocHash",  type: "bytes32" },
    ]}],
    stateMutability: "view",
  },
  { type: "function", name: "getRetirements", inputs: [{ name: "projectId", type: "uint256" }],
    outputs: [{ name: "", type: "tuple[]", components: [
      { name: "retirer",        type: "address" },
      { name: "beneficiary",    type: "address" },
      { name: "amount",         type: "uint256" },
      { name: "timestamp",      type: "uint256" },
      { name: "reason",         type: "string"  },
      { name: "registrySerial", type: "string"  },
    ]}],
    stateMutability: "view",
  },
  { type: "function", name: "MAX_SUPPLY_PER_PROJECT", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "feeRouter",              inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "feeToken",               inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "retirementFeePerCredit", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "balanceOf", inputs: [{ name: "account", type: "address" }, { name: "id", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "balanceOfBatch", inputs: [{ name: "accounts", type: "address[]" }, { name: "ids", type: "uint256[]" }],
    outputs: [{ name: "", type: "uint256[]" }], stateMutability: "view" },
  { type: "function", name: "uri", inputs: [{ name: "tokenId", type: "uint256" }], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "paused", inputs: [], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "isApprovedForAll", inputs: [{ name: "account", type: "address" }, { name: "operator", type: "address" }],
    outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "hasRole", inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "VERIFIER_ROLE", inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "supportsInterface", inputs: [{ name: "interfaceId", type: "bytes4" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  // Write functions
  { type: "function", name: "createProject", inputs: [
    { name: "name",             type: "string"  },
    { name: "methodology",      type: "string"  },
    { name: "region",           type: "string"  },
    { name: "vintage",          type: "uint256" },
    { name: "linkedPropertyId", type: "uint256" },
    { name: "uri_",             type: "string"  },
  ], outputs: [{ name: "projectId", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "verifyProject", inputs: [{ name: "projectId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "issueCredits", inputs: [
    { name: "projectId", type: "uint256" }, { name: "amount", type: "uint256" }, { name: "recipient", type: "address" },
  ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "retireCredits", inputs: [
    { name: "projectId",      type: "uint256" },
    { name: "amount",         type: "uint256" },
    { name: "beneficiary",    type: "address" },
    { name: "reason",         type: "string"  },
    { name: "registrySerial", type: "string"  },
  ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "retireCreditsFrom", inputs: [
    { name: "holder",         type: "address" },
    { name: "projectId",      type: "uint256" },
    { name: "amount",         type: "uint256" },
    { name: "beneficiary",    type: "address" },
    { name: "reason",         type: "string"  },
    { name: "registrySerial", type: "string"  },
  ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setFeeConfig", inputs: [
    { name: "feeRouter_",   type: "address" }, { name: "feeToken_", type: "address" }, { name: "feePerCredit_", type: "uint256" },
  ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setApprovalForAll", inputs: [{ name: "operator", type: "address" }, { name: "approved", type: "bool" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "pause",       inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "unpause",     inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "grantRole",   inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "revokeRole",  inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "safeTransferFrom", inputs: [
    { name: "from", type: "address" }, { name: "to", type: "address" }, { name: "id", type: "uint256" },
    { name: "amount", type: "uint256" }, { name: "data", type: "bytes" },
  ], outputs: [], stateMutability: "nonpayable" },
] as const;

// ─── PropertyNFT (ERC-1155 fractional property tokens, UUPS proxy) ───────────
// PropertyInfo struct: { maxSupply, name, location, jurisdiction, legalDocCID, createdAt, exists }
// Note: totalSupply(id) comes from ERC1155Supply, NOT the struct.
export const PropertyNFTAbi = [
  { type: "event", name: "PropertyCreated", inputs: [
    { name: "id",           type: "uint256", indexed: true  },
    { name: "name",         type: "string",  indexed: false },
    { name: "maxSupply",    type: "uint256", indexed: false },
    { name: "location",     type: "string",  indexed: false },
    { name: "jurisdiction", type: "string",  indexed: false },
  ]},
  { type: "event", name: "TokensMinted", inputs: [
    { name: "propertyId", type: "uint256", indexed: true  },
    { name: "to",         type: "address", indexed: true  },
    { name: "amount",     type: "uint256", indexed: false },
  ]},
  { type: "event", name: "MetadataUpdated", inputs: [
    { name: "propertyId", type: "uint256", indexed: true  },
    { name: "newURI",     type: "string",  indexed: false },
  ]},
  { type: "event", name: "TransferSingle", inputs: [
    { name: "operator", type: "address", indexed: true  },
    { name: "from",     type: "address", indexed: true  },
    { name: "to",       type: "address", indexed: true  },
    { name: "id",       type: "uint256", indexed: false },
    { name: "value",    type: "uint256", indexed: false },
  ]},
  { type: "event", name: "TransferBatch", inputs: [
    { name: "operator", type: "address",   indexed: true  },
    { name: "from",     type: "address",   indexed: true  },
    { name: "to",       type: "address",   indexed: true  },
    { name: "ids",      type: "uint256[]", indexed: false },
    { name: "values",   type: "uint256[]", indexed: false },
  ]},
  { type: "event", name: "ApprovalForAll", inputs: [
    { name: "account",  type: "address", indexed: true  },
    { name: "operator", type: "address", indexed: true  },
    { name: "approved", type: "bool",    indexed: false },
  ]},
  { type: "event", name: "RoleGranted", inputs: [
    { name: "role",    type: "bytes32", indexed: true },
    { name: "account", type: "address", indexed: true },
    { name: "sender",  type: "address", indexed: true },
  ]},
  { type: "event", name: "Paused",   inputs: [{ name: "account", type: "address", indexed: false }] },
  { type: "event", name: "Unpaused", inputs: [{ name: "account", type: "address", indexed: false }] },
  // Read functions
  { type: "function", name: "propertyCount", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getProperty", inputs: [{ name: "propertyId", type: "uint256" }],
    outputs: [{ name: "", type: "tuple", components: [
      { name: "maxSupply",    type: "uint256" },
      { name: "name",         type: "string"  },
      { name: "location",     type: "string"  },
      { name: "jurisdiction", type: "string"  },
      { name: "legalDocCID",  type: "string"  },
      { name: "createdAt",    type: "uint256" },
      { name: "exists",       type: "bool"    },
    ]}],
    stateMutability: "view",
  },
  { type: "function", name: "totalSupply", inputs: [{ name: "id", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "balanceOf", inputs: [{ name: "account", type: "address" }, { name: "id", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "balanceOfBatch", inputs: [{ name: "accounts", type: "address[]" }, { name: "ids", type: "uint256[]" }],
    outputs: [{ name: "", type: "uint256[]" }], stateMutability: "view" },
  { type: "function", name: "uri",    inputs: [{ name: "tokenId", type: "uint256" }], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "paused", inputs: [], outputs: [{ name: "", type: "bool"    }], stateMutability: "view" },
  { type: "function", name: "isApprovedForAll", inputs: [{ name: "account", type: "address" }, { name: "operator", type: "address" }],
    outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "hasRole",         inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "MINTER_ROLE",     inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "URI_MANAGER_ROLE",inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "supportsInterface",inputs: [{ name: "interfaceId", type: "bytes4" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  // Write functions
  { type: "function", name: "createProperty", inputs: [
    { name: "name",         type: "string"  },
    { name: "maxSupply",    type: "uint256" },
    { name: "location",     type: "string"  },
    { name: "jurisdiction", type: "string"  },
    { name: "metadataURI",  type: "string"  },
    { name: "legalDocCID",  type: "string"  },
  ], outputs: [{ name: "", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "mint", inputs: [
    { name: "to", type: "address" }, { name: "propertyId", type: "uint256" }, { name: "amount", type: "uint256" },
  ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "mintBatch", inputs: [
    { name: "to", type: "address" }, { name: "ids", type: "uint256[]" }, { name: "amounts", type: "uint256[]" },
  ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "updatePropertyURI", inputs: [{ name: "propertyId", type: "uint256" }, { name: "newURI", type: "string" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setApprovalForAll", inputs: [{ name: "operator", type: "address" }, { name: "approved", type: "bool" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "safeTransferFrom", inputs: [
    { name: "from", type: "address" }, { name: "to", type: "address" }, { name: "id", type: "uint256" },
    { name: "amount", type: "uint256" }, { name: "data", type: "bytes" },
  ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "pause",      inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "unpause",    inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "grantRole",  inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "revokeRole", inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }], outputs: [], stateMutability: "nonpayable" },
] as const;

// ─── StakingVault (4-tier OSANV staking, UUPS proxy) ─────────────────────────
// Tiers: 0=Bronze(800bps/30d), 1=Silver(1200bps/90d), 2=Gold(1800bps/180d), 3=Platinum(2200bps/365d)
// Tier struct:  { name, aprBps, lockDuration, totalStaked, exists }
// Stake struct: { tierIndex, amount, lockEnd, lastClaimTime }
export const StakingVaultAbi = [
  { type: "event", name: "Staked", inputs: [
    { name: "user",    type: "address", indexed: true  },
    { name: "tier",    type: "uint256", indexed: true  },
    { name: "amount",  type: "uint256", indexed: false },
    { name: "lockEnd", type: "uint256", indexed: false },
  ]},
  { type: "event", name: "Withdrawn", inputs: [
    { name: "user",      type: "address", indexed: true  },
    { name: "tier",      type: "uint256", indexed: true  },
    { name: "amount",    type: "uint256", indexed: false },
    { name: "earlyExit", type: "bool",    indexed: false },
    { name: "penalty",   type: "uint256", indexed: false },
  ]},
  { type: "event", name: "RewardsClaimed", inputs: [
    { name: "user",   type: "address", indexed: true  },
    { name: "tier",   type: "uint256", indexed: true  },
    { name: "amount", type: "uint256", indexed: false },
  ]},
  { type: "event", name: "RewardsDeposited", inputs: [
    { name: "sender", type: "address", indexed: true  },
    { name: "amount", type: "uint256", indexed: false },
  ]},
  { type: "event", name: "TierConfigUpdated", inputs: [
    { name: "tier",         type: "uint256", indexed: true  },
    { name: "aprBps",       type: "uint256", indexed: false },
    { name: "lockDuration", type: "uint256", indexed: false },
  ]},
  { type: "event", name: "PenaltyUpdated", inputs: [{ name: "penaltyBps", type: "uint256", indexed: false }] },
  { type: "event", name: "Paused",   inputs: [{ name: "account", type: "address", indexed: false }] },
  { type: "event", name: "Unpaused", inputs: [{ name: "account", type: "address", indexed: false }] },
  // Read functions
  { type: "function", name: "earned", inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getStakeInfo", inputs: [{ name: "account", type: "address" }],
    outputs: [
      { name: "tierIndex",      type: "uint256" },
      { name: "amount",         type: "uint256" },
      { name: "lockEnd",        type: "uint256" },
      { name: "pendingRewards", type: "uint256" },
    ], stateMutability: "view",
  },
  { type: "function", name: "tiers", inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "name",         type: "string"  },
      { name: "aprBps",       type: "uint256" },
      { name: "lockDuration", type: "uint256" },
      { name: "totalStaked",  type: "uint256" },
      { name: "exists",       type: "bool"    },
    ], stateMutability: "view",
  },
  { type: "function", name: "stakes", inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "tierIndex",     type: "uint256" },
      { name: "amount",        type: "uint256" },
      { name: "lockEnd",       type: "uint256" },
      { name: "lastClaimTime", type: "uint256" },
    ], stateMutability: "view",
  },
  { type: "function", name: "rewardPool",                 inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalStakedAcrossAllTiers",  inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "earlyWithdrawalPenaltyBps",  inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalRewardsDistributed",    inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "stakingToken",               inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "paused",                     inputs: [], outputs: [{ name: "", type: "bool"    }], stateMutability: "view" },
  { type: "function", name: "hasRole", inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "GOVERNANCE_ROLE", inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "EMERGENCY_ROLE",  inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "supportsInterface", inputs: [{ name: "interfaceId", type: "bytes4" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  // Write functions
  { type: "function", name: "stake", inputs: [{ name: "tierIndex", type: "uint256" }, { name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "withdraw", inputs: [{ name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "claimRewards", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "depositRewards", inputs: [{ name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "configureTier", inputs: [
    { name: "tierIndex", type: "uint256" }, { name: "aprBps", type: "uint256" }, { name: "lockDuration", type: "uint256" },
  ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setEarlyWithdrawalPenalty", inputs: [{ name: "penaltyBps", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "emergencyWithdraw", inputs: [{ name: "recipient", type: "address" }, { name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "pause",      inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "unpause",    inputs: [], outputs: [], stateMutability: "nonpayable" },
] as const;

// ─── Governance (DAO: 100K OSANV threshold, 5M quorum, 7d period, UUPS proxy) ─
// ProposalState: 0=Pending, 1=Active, 2=Defeated, 3=Succeeded, 4=Queued, 5=Executed, 6=Cancelled
// Proposal struct: { id, proposer, description, snapshotBlock, voteStart, voteEnd,
//                    forVotes, againstVotes, abstainVotes, state, executed }
// vote() support:  0=Against, 1=For, 2=Abstain
export const GovernanceAbi = [
  { type: "event", name: "ProposalCreated", inputs: [
    { name: "proposalId",   type: "uint256", indexed: true  },
    { name: "proposer",     type: "address", indexed: true  },
    { name: "description",  type: "string",  indexed: false },
    { name: "snapshotBlock",type: "uint256", indexed: false },
    { name: "voteStart",    type: "uint256", indexed: false },
    { name: "voteEnd",      type: "uint256", indexed: false },
  ]},
  { type: "event", name: "VoteCast", inputs: [
    { name: "voter",      type: "address", indexed: true  },
    { name: "proposalId", type: "uint256", indexed: true  },
    { name: "support",    type: "uint8",   indexed: false },
    { name: "weight",     type: "uint256", indexed: false },
  ]},
  { type: "event", name: "ProposalQueued", inputs: [
    { name: "proposalId",  type: "uint256", indexed: true  },
    { name: "executeAfter",type: "uint256", indexed: false },
  ]},
  { type: "event", name: "ProposalExecuted",  inputs: [{ name: "proposalId", type: "uint256", indexed: true }] },
  { type: "event", name: "ProposalCancelled", inputs: [{ name: "proposalId", type: "uint256", indexed: true }] },
  { type: "event", name: "ParametersUpdated", inputs: [
    { name: "votingDelay",    type: "uint256", indexed: false },
    { name: "votingPeriod",   type: "uint256", indexed: false },
    { name: "timelockDelay",  type: "uint256", indexed: false },
    { name: "quorum",         type: "uint256", indexed: false },
    { name: "threshold",      type: "uint256", indexed: false },
  ]},
  { type: "event", name: "Paused",   inputs: [{ name: "account", type: "address", indexed: false }] },
  { type: "event", name: "Unpaused", inputs: [{ name: "account", type: "address", indexed: false }] },
  // Read functions
  { type: "function", name: "getProposal", inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [{ name: "", type: "tuple", components: [
      { name: "id",            type: "uint256"  },
      { name: "proposer",      type: "address"  },
      { name: "description",   type: "string"   },
      { name: "snapshotBlock", type: "uint256"  },
      { name: "voteStart",     type: "uint256"  },
      { name: "voteEnd",       type: "uint256"  },
      { name: "forVotes",      type: "uint256"  },
      { name: "againstVotes",  type: "uint256"  },
      { name: "abstainVotes",  type: "uint256"  },
      { name: "state",         type: "uint8"    },
      { name: "executed",      type: "bool"     },
    ]}],
    stateMutability: "view",
  },
  { type: "function", name: "hasVoted",          inputs: [{ name: "proposalId", type: "uint256" }, { name: "voter", type: "address" }], outputs: [{ name: "", type: "bool"    }], stateMutability: "view" },
  { type: "function", name: "proposalCount",     inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "votingToken",       inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "votingDelay",       inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "votingPeriod",      inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "timelockDelay",     inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "quorumAmount",      inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "proposalThreshold", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "paused",            inputs: [], outputs: [{ name: "", type: "bool"    }], stateMutability: "view" },
  { type: "function", name: "hasRole", inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "EXECUTOR_ROLE",  inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "CANCELLER_ROLE", inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "supportsInterface", inputs: [{ name: "interfaceId", type: "bytes4" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  // Write functions
  { type: "function", name: "createProposal", inputs: [{ name: "description", type: "string" }],
    outputs: [{ name: "proposalId", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "vote", inputs: [{ name: "proposalId", type: "uint256" }, { name: "support", type: "uint8" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "queueProposal",   inputs: [{ name: "proposalId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "executeProposal", inputs: [{ name: "proposalId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "cancelProposal",  inputs: [{ name: "proposalId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "updateParameters", inputs: [
    { name: "votingDelay_",   type: "uint256" },
    { name: "votingPeriod_",  type: "uint256" },
    { name: "timelockDelay_", type: "uint256" },
    { name: "quorum_",        type: "uint256" },
    { name: "threshold_",     type: "uint256" },
  ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "pause",      inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "unpause",    inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "grantRole",  inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }], outputs: [], stateMutability: "nonpayable" },
] as const;

// ─── LandRegistry (dual government + indigenous authority verification, UUPS proxy)
// LandParcel struct: { parcelId, region, coordinates, owner, metadataHash, governmentTitleHash,
//   indigenousAuthority, governmentVerifier, verificationStatus(uint8), hasDispute,
//   tokenized, active, registeredAt, lastUpdatedAt }
// VerificationStatus: 0=Pending, 1=GovernmentVerified, 2=IndigenousVerified, 3=FullyVerified
export const LandRegistryAbi = [
  { type: "event", name: "ParcelRegistered", inputs: [
    { name: "propertyId",           type: "uint256", indexed: true  },
    { name: "parcelId",             type: "string",  indexed: false },
    { name: "region",               type: "string",  indexed: false },
    { name: "owner",                type: "address", indexed: true  },
    { name: "governmentTitleHash",  type: "bytes32", indexed: false },
    { name: "indigenousAuthority",  type: "address", indexed: false },
  ]},
  { type: "event", name: "GovernmentVerified", inputs: [
    { name: "propertyId", type: "uint256", indexed: true },
    { name: "verifier",   type: "address", indexed: true },
  ]},
  { type: "event", name: "IndigenousVerified", inputs: [
    { name: "propertyId", type: "uint256", indexed: true },
    { name: "authority",  type: "address", indexed: true },
  ]},
  { type: "event", name: "FullyVerified",  inputs: [{ name: "propertyId", type: "uint256", indexed: true }] },
  { type: "event", name: "DisputeFlagged", inputs: [
    { name: "propertyId", type: "uint256", indexed: true  },
    { name: "reason",     type: "string",  indexed: false },
    { name: "flaggedBy",  type: "address", indexed: true  },
  ]},
  { type: "event", name: "DisputeResolved", inputs: [
    { name: "propertyId", type: "uint256", indexed: true },
    { name: "resolvedBy", type: "address", indexed: true },
  ]},
  { type: "event", name: "ParcelTokenized",  inputs: [{ name: "propertyId", type: "uint256", indexed: true }] },
  { type: "event", name: "MetadataUpdated",  inputs: [
    { name: "propertyId", type: "uint256", indexed: true  },
    { name: "newHash",    type: "bytes32", indexed: false },
  ]},
  { type: "event", name: "RoleGranted", inputs: [
    { name: "role",    type: "bytes32", indexed: true },
    { name: "account", type: "address", indexed: true },
    { name: "sender",  type: "address", indexed: true },
  ]},
  // Read functions
  { type: "function", name: "parcelCount", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getParcel", inputs: [{ name: "propertyId", type: "uint256" }],
    outputs: [{ name: "", type: "tuple", components: [
      { name: "parcelId",            type: "string"  },
      { name: "region",              type: "string"  },
      { name: "coordinates",         type: "string"  },
      { name: "owner",               type: "address" },
      { name: "metadataHash",        type: "bytes32" },
      { name: "governmentTitleHash", type: "bytes32" },
      { name: "indigenousAuthority", type: "address" },
      { name: "governmentVerifier",  type: "address" },
      { name: "verificationStatus",  type: "uint8"   },
      { name: "hasDispute",          type: "bool"    },
      { name: "tokenized",           type: "bool"    },
      { name: "active",              type: "bool"    },
      { name: "registeredAt",        type: "uint256" },
      { name: "lastUpdatedAt",       type: "uint256" },
    ]}],
    stateMutability: "view",
  },
  { type: "function", name: "isFullyVerified",      inputs: [{ name: "propertyId", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "isGovernmentVerified",  inputs: [{ name: "propertyId", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "isIndigenousVerified",  inputs: [{ name: "propertyId", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "hasRole", inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "REGISTRAR_ROLE",        inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "VERIFIER_ROLE",         inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "DISPUTE_RESOLVER_ROLE", inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "PROPERTY_NFT_ROLE",     inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "supportsInterface", inputs: [{ name: "interfaceId", type: "bytes4" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  // Write functions
  { type: "function", name: "registerParcel", inputs: [
    { name: "propertyId",          type: "uint256" },
    { name: "parcelId",            type: "string"  },
    { name: "region",              type: "string"  },
    { name: "coordinates",         type: "string"  },
    { name: "metadataHash",        type: "bytes32" },
    { name: "governmentTitleHash", type: "bytes32" },
    { name: "indigenousAuthority", type: "address" },
  ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "verifyGovernment", inputs: [{ name: "propertyId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "verifyIndigenous", inputs: [{ name: "propertyId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "flagDispute", inputs: [
    { name: "propertyId", type: "uint256" }, { name: "reason", type: "string" },
  ], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "resolveDispute", inputs: [{ name: "propertyId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "markTokenized",  inputs: [{ name: "propertyId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "grantRole",  inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "revokeRole", inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }], outputs: [], stateMutability: "nonpayable" },
] as const;
