[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
carbon = "H2hzHypyQxJpDiGWgpYSDN56JdyLzpPkrHcAD2cxnZUb"
landbank = "FRsKDe4vdmRczcXSvub2oAgCgs4uo4LttxvXrwfg1NkT"
minerals = "6oNLPSirAwbmTohpfUtUk2UHSLfsVnvHguP9ZdwcGRzF"
oracle = "9x81xZ2Kqjc5zbVAsX7Kqwv4HSo1HSkWkC3LUorZ8n55"
osanvault_core = "5bNkJDyJaE3rZ93ahWaA8MPTxQvCG6dC9jkTanLV2qRF"
osanvault_lend = "3ZX5svRbpgvNVQXpwj7cQG2MZs97KVnV3azCkSiwU3CR"
reits = "EUJWumAPhQVeTK3CAuBKh9SFf1AvqrmvTty37RKJxmf1"

[programs.localnet]
carbon = "H2hzHypyQxJpDiGWgpYSDN56JdyLzpPkrHcAD2cxnZUb"
landbank = "FRsKDe4vdmRczcXSvub2oAgCgs4uo4LttxvXrwfg1NkT"
minerals = "6oNLPSirAwbmTohpfUtUk2UHSLfsVnvHguP9ZdwcGRzF"
oracle = "9x81xZ2Kqjc5zbVAsX7Kqwv4HSo1HSkWkC3LUorZ8n55"
osanvault_core = "5bNkJDyJaE3rZ93ahWaA8MPTxQvCG6dC9jkTanLV2qRF"
osanvault_lend = "3ZX5svRbpgvNVQXpwj7cQG2MZs97KVnV3azCkSiwU3CR"
reits = "EUJWumAPhQVeTK3CAuBKh9SFf1AvqrmvTty37RKJxmf1"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build = "anchor build"
deploy = "anchor deploy --provider.cluster devnet"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]

[test]
startup_wait = 60000
shutdown_wait = 2000
upgradeable = false
