server {
    listen 80;
    server_name osanvaultafrica.com www.osanvaultafrica.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name osanvaultafrica.com www.osanvaultafrica.com;

    ssl_certificate ~/osanvault-africa/ssl/osanvaultafrica.com.crt;
    ssl_certificate_key ~/osanvault-africa/ssl/osanvaultafrica.com.key;

    root ~/osanvault-africa/landing;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
