name: Auto Deploy ÒsánVault Africa Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install requests

      - name: Fetch NET Token Data
        run: python3 scripts/fetch-net-data.py

      - name: Generate Website Pages
        run: python3 scripts/generate-pages.py

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add site/
          git commit -m "⚡ Auto-update website" || echo "No changes to commit"
          git push origin main

      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: site
      - uses: actions/deploy-pages@v2
