name: Secret Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run secret scanner
        uses: trufflesecurity/trufflehog@v3
        with:
          path: .
          entropy: true
          rules: github,slack,aws,azure,gcp,twilio,openai,cloudflare

      - name: Fail on secrets
        run: |
          if [ -s trufflehog_results.json ]; then
            echo "❌ Potential secret found! Resolve before merging."
            cat trufflehog_results.json
            exit 1
          else
            echo "✅ No secrets found. Safe to merge."
          fi
